### ISSUE TITLE
(BUG) Game does not save when leaving a planet.

### ISSUE THREAD

**Issue by TheComicRelief** [LethalCompanyModding/Enhancer#10]
Game doesn't save when leaving planets resulting in softlock. Modpack code: 01904f09-1e09-0a02-8129-0a59413ec885

[10:49:10.9661310] [Info   :  Enhancer] ProtectionPatch -> False : False
[10:49:10.9931150] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Unity.Netcode.NetworkList`1[T].Clear () (at <895801699cfc4b4ab52267f31e2a4998>:IL_0023)
SCP956.Patches.RoundManagerPatch.DespawnPropsAtEndOfRoundPostfix () (at ./Patches/RoundManagerPatch.cs:99)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::DespawnPropsAtEndOfRound>(RoundManager,bool)
StartOfRound+<EndOfGame>d__262.MoveNext () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_0213)
LobbyControl.Patches.NetworkPatcher+<ReopenSteamLobby>d__6.MoveNext () (at ./src/Patches/NetworkPatcher.cs:167)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[10:49:10.9931150] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Unity.Netcode.NetworkList`1[T].Clear () (at <895801699cfc4b4ab52267f31e2a4998>:IL_0023)
SCP956.Patches.RoundManagerPatch.DespawnPropsAtEndOfRoundPostfix () (at ./Patches/RoundManagerPatch.cs:99)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::DespawnPropsAtEndOfRound>(RoundManager,bool)
StartOfRound+<EndOfGame>d__262.MoveNext () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_0213)
LobbyControl.Patches.NetworkPatcher+<ReopenSteamLobby>d__6.MoveNext () (at ./src/Patches/NetworkPatcher.cs:167)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by TheComicRelief** [comment]
Happens specifically at the last day of meeting quota. Edited: More testing reveals that it happens when store items are left on planet when leaving, otherwise nothing happens

**Comment by RobynLlama** [comment]
I'm not really sure I can help with this. `LobbyControl.Patches.NetworkPatcher` is not from Enhancer and `src/Patches/NetworkPatcher.cs` does not exist in this project. This looks like something called LobbyControl is doing something? That or `SCP956.Patches.RoundManagerPatch.DespawnPropsAtEndOfRoundPostfix` from SCP956 also has its own DespawnProps method that may be interfering with either Enhancer or LobbyControl. I don't know, never used those mods.

My best guess is that one of those two other mods is also modifying items at the end of the round to preserve them and there really isn't much I can do to fix that. Specifically it looks like SCP956 has a postfix to change the way despawnprops works and I prefix that method and stop it from running. The default behavior of that method is to wipe all items at the end of the round and I preserve a few items for you depending on your setting in Enhancer so other mods that also want to change what stays at the end of the round will fail. This may simply be an unsolvable conflict between Enhancer and the SCP956 or LobbyControl.

Enhancer requires taking control of the despawnprops method in order to stop certain ones from being deleted for you with scrap protection and it looks like 965 depends on its code running after despawnprops normally does. My best advice is to simply pick one of the two to use and uninstall the other.
