### ISSUE TITLE
Remove the "Cannot pickup until ship is landed" restriction on items after game load

### ISSUE THREAD

**Issue by RobynLlama** [LethalCompanyModding/Enhancer#2]
I don't understand what purpose this serves since it never comes back after the ship has landed at least once. I'd like to be able to pick up my flashlight and shovel before choosing a moon to land on on first load, thanks!

**Comment by Lordfirespeed** [comment]
I believe this is a feature intended for public lobbies, where there's a possibility that people could join, pick up your items, and leave, which in some situations might cause those items to be deleted. 

It doesn't come back after the ship has first landed because (in Vanilla, at least) players cannot join after the ship has first landed.

**Comment by Roobotics** [comment]
Picking up items before others join the lobby, causes visual desync mostly, they see an item where it was, if you picked it up before they joined. It just stays there forever for them usually.

**Comment by RobynLlama** [comment]
Oh. Thanks for letting me know. This mod is in maintenance mode but I'm happy to have learned something today

**Comment by Roobotics** [comment]
No problem! Also FYI, I think your mod is the few ones that features a coin-flip/RNG for scrap-loss. It's both saved and decimated my runs alike and I'm here for it. Saving all scrap like so many other mods do, is just kinda broken, but losing it all is instantly game-over last day, and that's pretty bad also from a game-design standpoint. You found a good middle-ground with that option!
