### ISSUE TITLE
Terminal screen persisting even with the setting off 

### ISSUE THREAD

**Issue by Yerningcross8** [LethalCompanyModding/Enhancer#6]
I have the setting for AlwaysShowTerminal as false but it still keeps the terminal on screen everytime I use it, which is pretty annoying as it gets in the way.

**Comment by RobynLlama** [comment]
Hello, I had a report of something like this happening before. If you are in the Modding Discord you may follow this link to view it: https://discord.com/channels/1168655651455639582/1169069074572116041/1178867766787330088
The user reported the terminal window was being drawn to the screen with this setting set to false but it turned out to be a conflict with another mod. Sadly, they never reported back which one was doing it so I have no idea what it could be.

**Comment by RobynLlama** [comment]
fixed ages ago but I forgor to close this
